Repository dsc-iem/Tourist-Guiding-App-Hacktoberfest22, pull requests merged in 2022-10, with the labels that each got.

#2 PPT added
  Tourist-Guider-App-PPT.pptx
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Entity Class Added.
  tg-nx-backend/.gitignore
  tg-nx-backend/.mvn/wrapper/maven-wrapper.jar
  tg-nx-backend/.mvn/wrapper/maven-wrapper.properties
  tg-nx-backend/mvnw
  tg-nx-backend/mvnw.cmd
  tg-nx-backend/pom.xml
  tg-nx-backend/src/main/java/com/tourist/app/AppApplication.java
  tg-nx-backend/src/main/java/com/tourist/app/entity/User.java
  tg-nx-backend/src/main/resources/application.properties
  tg-nx-backend/src/test/java/com/tourist/app/AppApplicationTests.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 added face reg startup modules
  face-reg/image_comparison.py
  face-reg/images/Elon Musk.jpg
  face-reg/images/Jeff Bezoz.jpg
  face-reg/images/Messi.webp
  face-reg/images/Ryan Reynolds.jpg
  face-reg/images/Sergio Canu.png
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#8 added dependency file
  face-reg/main_video.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Entity changed into Jpa from Mongo
  tg-nx-backend/src/main/java/com/tourist/app/entity/User.java
  tg-register-backend/.gitignore
  tg-register-backend/.mvn/wrapper/maven-wrapper.jar
  tg-register-backend/.mvn/wrapper/maven-wrapper.properties
  tg-register-backend/mvnw
  tg-register-backend/mvnw.cmd
  tg-register-backend/pom.xml
  tg-register-backend/src/main/java/com/tourist/app/AppApplication.java
  tg-register-backend/src/main/java/com/tourist/app/entity/User.java
  tg-register-backend/src/main/resources/application.properties
  tg-register-backend/src/test/java/com/tourist/app/AppApplicationTests.java
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 another webp file for testing with a dependency file
  face-reg/Messi1.webp
  face-reg/simple_facerec.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Changed from MongoRepository to JpaRepo
  tg-register-backend/src/main/java/com/tourist/app/repository/UserRepository.java
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 Service Interface added and Repo rectified
  tg-register-backend/src/main/java/com/tourist/app/repository/UserRepository.java
  tg-register-backend/src/main/java/com/tourist/app/service/UserInterface.java
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, fix

#13 Service Layer added on full terms
  tg-register-backend/src/main/java/com/tourist/app/service/UserInterface.java
  tg-register-backend/src/main/java/com/tourist/app/serviceimpl/UserImpl.java
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
